#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
# With a sleep 2 in between each iteration and I am invincible!!! when receiving a SIGTERM signal


trap "echo 'I am invincible!!!'" SIGTERM
count=0

while [ $count -ge 0 ]
do
	echo "To infinity and beyond"
	sleep 2
done
