#!/usr/bin/env bash
# Bash script that loops from 1 to 20 and displays 4 and bad luck from China for the 4th loop iteration,9 and good luck Japan for the 9th loop iteration and 17 bad luck from Italy for the other iterations

count=1

while [ $count -le 20 ]
do
	echo $count
	case $count in
		4)
		 echo "bad luck from China"
		 ;;
		9)
		 echo "bad luck from Japan"
		 ;;
		17)
		 echo "bad luck from Italy"
		 ;;
	esac
	((count++))
done
